test_that("endpoint profiles match stable IDs and use the displayed coordinates", {
  asset <- list(sample_ids = c("pure", "mixture", "no-reference"),
    taxon_names = c("Lactobacillus_iners", "Lactobacillus_crispatus", "Taxon_C"),
    indices = list(1L, c(1L, 3L, 2L), 2L), abundances = list(1, c(.8, .15, .05), 1))
  asset <- gflowui_validate_vertex_hover(asset)
  ids <- c("mixture", "pure", "no-reference")
  a <- gflowui_endpoint_abundance_profile(1L, ids, asset)
  expect_identical(a$sample_id, "mixture")
  expect_identical(a$label, "Lactobacillus iners; Taxon C")
  expect_equal(a$profile$abundance, c(.8, .15, .05))
  r <- gflowui_endpoint_abundance_profile(1L, ids, asset, "ratio", "Lactobacillus_iners")
  expect_identical(r$label, "Taxon C / Lactobacillus iners; Lactobacillus crispatus / Lactobacillus iners")
  expect_equal(r$profile$abundance, c(.15, .05)/.8)
  expect_identical(r$profile_value_label, "reference ratio")
  s <- gflowui_endpoint_abundance_profile(1L, ids, asset, "sqrt_ratio", "Lactobacillus_crispatus")
  expect_equal(s$profile$abundance, sqrt(c(.8, .15)/.05))
  expect_identical(s$profile$feature[1], "sqrt(Lactobacillus iners / Lactobacillus crispatus)")
  pure <- gflowui_endpoint_abundance_profile(2L, ids, asset, "ratio", "Lactobacillus_iners")
  expect_identical(pure$label, "Pure Lactobacillus iners (chart origin)")
  expect_equal(nrow(pure$profile), 0L)
  expect_null(gflowui_endpoint_abundance_profile(3L, ids, asset, "ratio", "Lactobacillus_iners"))
  expect_null(gflowui_endpoint_abundance_profile(4L, ids, asset))
  expect_null(gflowui_endpoint_abundance_profile(1L, "missing", asset))
})
