# Human-readable definitions; numeric results remain in the saved result assets.
gflowui_ec_definitions_ui <- function() {
  formula <- function(tex) shiny::div(style="overflow-x:auto; padding: .25rem 0;", paste0("\\[",tex,"\\]"))
  item <- function(title,tex,text) shiny::tagList(shiny::h5(title),formula(tex),shiny::p(text))
  group <- function(title,...) shiny::tags$details(shiny::tags$summary(title),...)
  # SVG output keeps calligraphic and set-operation glyphs independent of browser fonts.
  math <- function(...) shiny::tagList(
    shiny::tags$head(shiny::singleton(shiny::tags$script(src=paste0(
      getOption("shiny.mathjax.url","https://mathjax.rstudio.com/latest/MathJax.js"),
      "?config=TeX-AMS-MML_SVG")))), ...,
    shiny::tags$script(shiny::HTML("if(window.MathJax && MathJax.Hub) MathJax.Hub.Queue(['Typeset',MathJax.Hub]);")))
  math(shiny::div(class="ec-metric-definitions",
    shiny::p("Embedding-quality scores evaluate a drawing. Vertex and edge measures describe the saved graph and stay fixed when the drawing changes."),
    group("Vertex and edge notation",
      shiny::p(r"(The saved graph \(G=(V,E)\) is simple, undirected and has unit edge lengths. \(\mathcal N(v)\) is the neighbor set of vertex \(v\); \(C\) is its connected component and \(n_C=|C|\). \(d_G(i,j)\) is shortest-path length. \(s<t\) counts each unordered pair once. \(\binom q2=q(q-1)/2\).)"),
      shiny::p(r"(\(G-e\) removes only edge \(e\). \(G-v\) removes vertex \(v\) and its incident edges. \(c(G)\) counts components, including isolates; \(\mathbf1\{S\}\) is 1 if statement \(S\) holds and 0 otherwise. Original matrix coefficients are not used as distances.)")),
    group("Edge measures",
      item("Detour ratio",r"(R_{ij}=\frac{d_{G-\{e\}}(i,j)}{\ell_{ij}},\qquad e=\{i,j\},\quad\ell_{ij}=1)",
        "Length of the shortest replacement route. Finite values are at least 2. A bridge has infinite detour, shown in red; infinity is not replaced by a large finite number."),
      item("Edge betweenness",r"(B_E(e)=\sum_{\substack{s<t\\s,t\in C}}\frac{\sigma_{st}(e)}{\sigma_{st}})",
        r"(\(\sigma_{st}\) counts shortest paths and \(\sigma_{st}(e)\) counts those using the edge. Each reachable pair sends one unit of demand, split equally between tied paths. The edge's own endpoint pair is included.)"),
      item("Component-normalized edge betweenness",r"(\widehat B_E(e)=\frac{B_E(e)}{\binom{n_C}{2}})",
        "Fraction of a uniformly chosen component pair's demand carried by the edge; between 0 and 1. Normalization compares relative traffic within each component."),
      item("Triangle count",r"(t_{ij}=|\mathcal N(i)\cap\mathcal N(j)|)",
        "Number of common neighbors, each providing a two-edge replacement route. Zero does not rule out longer alternative routes."),
      item("Effective resistance",r"(r^{\mathrm{eff}}_{ij}=(\mathbf e_i-\mathbf e_j)^{\mathsf T}L^+(\mathbf e_i-\mathbf e_j))",
        r"(Replace each edge by a one-ohm resistor. This is the voltage difference needed to send unit current from \(i\) to \(j\). \(L=D-A\), where \(A\) is binary adjacency and \(D\) is diagonal degree; \(L^+\) is its Moore–Penrose pseudoinverse and \(\mathbf e_i\) is a unit coordinate vector. Existing edges have \(0<r^{\mathrm{eff}}\le1\): bridges equal 1, while alternative routes lower resistance.)"),
      item("Bridge status",r"(b_e=\mathbf1\{c(G-e)>c(G)\})",
        "One means that deleting this edge disconnects its component; zero means it does not."),
      item("Bridge separation sizes",r"(s_e=\min(a,n_C-a),\qquad l_e=\max(a,n_C-a))",
        r"(Deleting a bridge leaves pieces of sizes \(a\) and \(n_C-a\). These are their smaller and larger vertex counts. For nonbridges the sizes are not applicable, shown in gray.)"),
      item("Pairs separated by a bridge",r"(P_e=\begin{cases}s_e l_e,&b_e=1,\\0,&b_e=0.\end{cases})",
        r"(Number of formerly connected unordered pairs disconnected by deleting the edge. For a bridge, \(B_E(e)=P_e\). These separation fields belong to the bridge measure family.)")),
    group("Vertex measures",
      item("Degree",r"(d_v=|\mathcal N(v)|)","Number of immediate neighbors. Isolates have degree zero; leaves have degree one."),
      item("Vertex betweenness",r"(B_V(v)=\sum_{\substack{s<t\\s,t\in C\setminus\{v\}}}\frac{\sigma_{st}(v)}{\sigma_{st}})",
        r"(\(\sigma_{st}(v)\) counts shortest paths that pass through \(v\). Traffic starting or ending at \(v\) is excluded; tied paths split credit equally.)"),
      item("Component-normalized vertex betweenness",r"(\widehat B_V(v)=\begin{cases}\dfrac{B_V(v)}{\binom{n_C-1}{2}},&n_C\ge3,\\0,&n_C<3.\end{cases})",
        "Between 0 and 1. The denominator counts possible endpoint pairs after excluding the measured vertex."),
      item("Core number",r"(\kappa(v)=\max\{k\ge0:v\in V(H_k)\})",
        r"(\(H_k\) is the maximal induced subgraph with every vertex of degree at least \(k\) within it. Repeatedly remove vertices with fewer than \(k\) remaining neighbors. The largest integer threshold survived by \(v\) is its core number; isolates have zero.)"),
      item("Local clustering",r"(C_v=\begin{cases}\dfrac{2T_v}{d_v(d_v-1)},&d_v\ge2,\\0,&d_v<2.\end{cases})",
        r"(\(T_v=\frac12\sum_{u\in\mathcal N(v)}t_{uv}\) counts triangles containing \(v\). Clustering is the fraction of neighbor pairs that are connected; between 0 and 1. Degree below two is assigned zero.)"),
      item("Articulation point",r"(a_v=\mathbf1\{c(G-v)>c(G)\})",
        "One means deleting the vertex splits its component. Leaves and isolates are not articulation points. A graph can have an articulation point without any bridges.")),
    group("Embedding-quality measures",
      shiny::p(r"(For component \(C\), \(S_C\) is the set of evaluated unordered pairs; \(N_C=\binom{n_C}{2}\), \(m_C=|S_C|\), and \(w_C=N_C/m_C\). Exact evaluation uses all pairs and \(w_C=1\); sampled evaluation uses the shared uniform pairs. Cross-component pairs are excluded.)"),
      formula(r"(d_{ij}=d_G(i,j),\qquad r_{ij}=\|z_i-z_j\|_2)"),
      shiny::p(r"(\(z_i\) is the displayed coordinate vector before component packing. \(p_{ij}\) is the sum of drawn edge lengths along the fixed original shortest route from \(i\) to \(j\). In the formulas below, each inner sum is over \((i,j)\in S_C\); outer sums are over components with pairs.)"),
      item("Euclidean distance error (lower is better)",r"(s_C=\frac{\sum r_{ij}d_{ij}}{\sum r_{ij}^2},\qquad E_d=\sqrt{\frac{\sum_C w_C\sum(s_Cr_{ij}-d_{ij})^2}{\sum_Cw_C\sum d_{ij}^2}})",
        "Relative root-squared chord-distance error after fitting a scale separately in each component. Zero is perfect. Coincident coordinates make the fitted scale undefined."),
      item("Relative stress (lower is better)",r"(a_C=\frac{\sum(r_{ij}/d_{ij})}{\sum(r_{ij}/d_{ij})^2},\qquad E_r=\frac{\sum_Cw_C\sum(a_Cr_{ij}/d_{ij}-1)^2}{\sum_CN_C})",
        "Mean squared relative distance error, with its own fitted scale per component. Zero is perfect; this is not the same scale fit as Euclidean error."),
      item("Fixed-path error (lower is better)",r"(E_p=\sqrt{\frac{\sum_Cw_C\sum(p_{ij}-d_{ij})^2}{\sum_Cw_C\sum d_{ij}^2}})",
        "Uses fixed original shortest routes and identity scale. Zero means these routes retain their lengths, which alone does not establish unfolding."),
      item("Edge error (lower is better)",r"(E_e=\sqrt{\frac1{|E|}\sum_{\{i,j\}\in E}(\|z_i-z_j\|_2-1)^2})",
        "Root mean squared error of drawn edge lengths relative to unit graph lengths. All edges are evaluated, without fitting a scale."),
      item("Distance-rank correlation (higher is better)",r"(\rho=\operatorname{Corr}(\operatorname{rank}(d),\operatorname{rank}(r)))",
        "Spearman correlation on evaluated pairs, using average ranks for ties. One means identical rank order; constant ranks are undefined. Disconnected graphs retain separate component correlations."),
      item("Trustworthiness and continuity (higher is better)",r"(T(k)=1-f_C\sum_i\sum_{j\in U_i}(q^G_{ij}-k))",
        r"(\(U_i\) contains neighbors among the embedding's nearest \(k\) that are absent from the graph's nearest \(k\). \(q^G_{ij}\) is the graph-distance rank of \(j\) around \(i\), excluding \(i\). Trustworthiness penalizes these false neighbors.)"),
      formula(r"(K(k)=1-f_C\sum_i\sum_{j\in W_i}(q^Z_{ij}-k),\quad f_C=\frac{2}{n_Ck(2n_C-3k-1)})"),
      shiny::p(r"(\(W_i\) contains graph neighbors missing from the embedding's nearest \(k\); \(q^Z_{ij}\) is the embedded-distance rank. Continuity penalizes these lost neighbors. One is perfect. Scores use \(k\in\{5,10,20,50\}\) with \(k<n_C/2\), lexical vertex-ID tie breaking and exact neighborhoods. Valid component scores are averaged with vertex-count weights.)")),
    group("Evaluation and interpretation",
      lapply(c("evaluation","interpretation","uncertainty"),function(k)shiny::p(gflowui_ec_definitions()[[k]])),
      shiny::p("Structural values describe connectivity, not universal scientific importance. Their meaning depends on how each graph was constructed. Structural color ranges are fixed for each graph, but may differ between graphs.")),
    group("References",
      shiny::p(shiny::a("Brandes: betweenness computation",href="https://doi.org/10.1080/0022250X.2001.9990249",target="_blank")),
      shiny::p(shiny::a("Spielman and Srivastava: effective resistance",href="https://doi.org/10.1137/080734029",target="_blank")),
      shiny::p(shiny::a("Batagelj and Zaversnik: core decomposition",href="https://arxiv.org/abs/cs/0310049",target="_blank")))
  ))
}
